openapi: 3.0.0
info:
  title: section_9_jobs_api
  version: 1.0.0
servers:
  - url: http://{{localhostapiv1}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /auth/register:
    post:
      tags:
        - General
      summary: POST register user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: anna
                email: anna@gmail.com
                password: '123456'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - General
      summary: POST login user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: john8@gmail.com
                password: '123456'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /jobs:
    post:
      tags:
        - General
      summary: POST create job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: googley
                position: dev
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - General
      summary: GET get all jobs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /jobs/654a8c57fc5d6824c35a90b9:
    get:
      tags:
        - General
      summary: GET get job
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - General
      summary: PATCH update job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: googleyedit2
                position: devvvvvv
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - General
      summary: DELETE delete job
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
